---
# Copyright (C) 2023 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Create directory for kubeconfig files
  ansible.builtin.file:
    path: "{{ k8s_encryption_config_directory }}"
    owner: "{{ k8s_encryption_config_owner }}"
    group: "{{ k8s_encryption_config_group }}"
    mode: "{{ k8s_encryption_config_directory_perm }}"
    state: directory

- name: Create encryption config file
  ansible.builtin.template:
    src: "templates/encryption-config.yml.j2"
    dest: "{{ k8s_encryption_config_directory }}/encryption-config.yaml"
    mode: "0600"

- name: Set file permissions
  ansible.builtin.file:
    path: "{{ k8s_encryption_config_directory }}/encryption-config.yaml"
    owner: "{{ k8s_encryption_config_owner }}"
    group: "{{ k8s_encryption_config_group }}"
    mode: '{{ k8s_encryption_config_file_perm }}'
    modification_time: "preserve"
    access_time: "preserve"
