---
- block:
    - name: Assert the configuration is provided
      ansible.builtin.assert:
        that:
          - cilium_bgp_config is defined
          - cilium_bgp_config != None
    - name: Add BGP configuration
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: bgp-config
            namespace: "{{ cilium_namespace }}"
          data:
            config.yaml: "{{ cilium_bgp_config }}"
  delegate_to: 127.0.0.1
  run_once: true
