---
- name: Uninstall release via Helm
  kubernetes.core.helm:
    name: "{{ cilium_release_name }}"
    release_namespace: "{{ cilium_namespace }}"
    state: absent
  run_once: true
  delegate_to: "{{ cilium_delegate_to }}"
  register: cilium__helm_show_uninstall_release

- name: Uninstall release via Helm (helm command executed)
  when:
    - cilium__helm_show_uninstall_release is defined
    - cilium__helm_show_uninstall_release.command is defined
    - cilium_helm_show_commands
  ansible.builtin.debug:
    var: cilium__helm_show_uninstall_release.command
  delegate_to: "{{ cilium_delegate_to }}"
  run_once: true

- name: Delete Cilium etcd secrets in k8s
  kubernetes.core.k8s:
    state: absent
    name: "{{ cilium_etcd_secrets_name }}"
    namespace: "{{ cilium_namespace }}"
    api_version: v1
    kind: Secret
  delegate_to: "{{ cilium_delegate_to }}"
  run_once: true

- name: BPFFS handling for Ubuntu 18.04
  when:
    - ansible_lsb.release is defined
    - ansible_lsb.release is version('20.04', '<')
  block:
    - name: Disable and umount BPFFS
      ansible.builtin.service:
        name: sys-fs-bpf.mount
        enabled: false
        state: stopped

    - name: Remove systemd unit file for mounting BPFFS
      ansible.builtin.file:
        path: "/etc/systemd/system/sys-fs-bpf.mount"
        state: absent
      notify:
        - Reload systemd

- name: Delete namespace used by Cilium
  kubernetes.core.k8s:
    name: "{{ cilium_namespace }}"
    api_version: v1
    kind: Namespace
    state: absent
  delegate_to: "{{ cilium_delegate_to }}"
  run_once: true
