---
- name: Delete Cilium resources via Helm
  ansible.builtin.shell:
    set -o errexit
    set -o pipefail
    set -o nounset

    helm uninstall {{ cilium_release_name }} --namespace {{ cilium_namespace }}

    exit 0
  run_once: true
  delegate_to: 127.0.0.1
  changed_when: false
  args:
    executable: "/bin/bash"

- name: Delete Cilium etcd secrets in k8s
  kubernetes.core.k8s:
    state: absent
    definition: "{{ lookup('template', 'etcd-secrets.yml.j2') }}"
    namespace: "{{ cilium_namespace }}"
  delegate_to: 127.0.0.1
  run_once: true
  when: cilium_etcd_secrets_name is defined

- name: BPFFS handling for Ubuntu 18.04
  block:
    - name: Disable and umount BPFFS
      ansible.builtin.service:
        name: sys-fs-bpf.mount
        enabled: false
        state: stopped

    - name: Remove systemd unit file for mounting BPFFS
      ansible.builtin.file:
        path: "/etc/systemd/system/sys-fs-bpf.mount"
        state: absent
      notify:
        - Reload systemd
  when:
    - ansible_lsb.release is defined
    - ansible_lsb.release is version('20.04', '<')

- name: Delete namespace used by Cilium
  kubernetes.core.k8s:
    name: "{{ cilium_namespace }}"
    api_version: v1
    kind: Namespace
    state: absent
  delegate_to: 127.0.0.1
  run_once: true
