---
# Copyright (C) 2020-2025 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Pre flight pod check
  block:
    - name: Waiting for pre flight deployment
      ansible.builtin.wait_for:
        timeout: 10
      run_once: true

    - name: Fetch current Cilium pre flight DaemonSet state
      kubernetes.core.k8s_info:
        api_version: v1
        kind: DaemonSet
        name: cilium-pre-flight-check
        namespace: "{{ cilium_namespace }}"
      register: cilium_pre_flight_check_daemonset
      until:
        - cilium_pre_flight_check_daemonset.resources | default([]) | length > 0
        - (cilium_pre_flight_check_daemonset.resources[0].status.numberReady | default(0) | int) == (cilium_pods_running | int)
      retries: 60
      delay: 10
      run_once: true
      delegate_to: "{{ cilium_delegate_to }}"

    - name: Register current Cilium pre flight pods running
      ansible.builtin.set_fact:
        cilium_pre_flight_pods_running: "{{ cilium_pre_flight_check_daemonset.resources[0].status.numberReady | default(0) | int }}"
      run_once: true
      delegate_to: "{{ cilium_delegate_to }}"
