---
# Copyright (C) 2022 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt

platforms:
  - name: test-cilium-ubuntu2004
    box: generic/ubuntu2004
    memory: 4096
    cpus: 2
    groups:
      - ubuntu
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.10

provisioner:
  name: ansible
  connection_options:
    ansible_ssh_user: vagrant
  log: true
  lint: yamllint . && flake8 && ansible-lint
  inventory:
    host_vars:
      test-cilium-ubuntu2004:
        ansible_python_interpreter: "/usr/bin/python3"
        cilium_etcd_enabled: "false"
        cilium_delegate_to: test-cilium-ubuntu2004
        cilium_helm_show_commands: true
        containerd_flavor: "k8s"
        containerd_tmp_directory: "/tmp"
        containerd_runc_binary_directory: "/usr/local/sbin"
        containerd_crictl_config_file: "crictl.yaml"
        containerd_crictl_config_directory: "/etc"
        containerd_cni_binary_directory: "/opt/cni/bin"
        minikube_version: 1.31.2
        dockerd_settings_user:
          "log-level": "info"
          "iptables": "true"
          "ip-masq": "true"
          "mtu": "1500"

scenario:
  name: default
  test_sequence:
    - prepare
    - converge

verifier:
  name: ansible
  enabled: true
