---
# Copyright (C) 2022 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt

platforms:
  - name: test-assets
    box: generic/ubuntu2204
    memory: 2048
    cpus: 2
    groups:
      - vpn
      - k8s_assets
      - k8s
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.5
  - name: test-controller1
    box: generic/ubuntu2204
    memory: 2048
    cpus: 2
    groups:
      - vpn
      - haproxy
      - k8s_controller
      - k8s_worker
      - k8s
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.10
  - name: test-controller2
    box: generic/ubuntu2204
    memory: 2048
    cpus: 2
    groups:
      - vpn
      - haproxy
      - k8s_controller
      - k8s_worker
      - k8s
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.20
  - name: test-controller3
    box: generic/ubuntu2204
    memory: 2048
    cpus: 2
    groups:
      - vpn
      - k8s_controller
      - k8s_worker
      - k8s
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.30
  - name: test-etcd1
    box: generic/ubuntu2204
    memory: 2048
    cpus: 2
    groups:
      - vpn
      - k8s_etcd
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.100
  - name: test-etcd2
    box: generic/ubuntu2204
    memory: 2048
    cpus: 2
    groups:
      - vpn
      - k8s_etcd
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.110
  - name: test-etcd3
    box: generic/ubuntu2204
    memory: 2048
    cpus: 2
    groups:
      - vpn
      - k8s_etcd
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.120
  - name: test-worker1
    box: generic/ubuntu2204
    memory: 2048
    cpus: 2
    groups:
      - vpn
      - haproxy
      - k8s_worker
      - k8s
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.200
  - name: test-worker2
    box: generic/ubuntu2204
    memory: 2048
    cpus: 2
    groups:
      - vpn
      - k8s_worker
      - k8s
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.210

provisioner:
  name: ansible
  connection_options:
    ansible_ssh_user: vagrant
    ansible_become: true
  log: true
  lint: yamllint . && flake8 && ansible-lint

scenario:
  name: default
  test_sequence:
    - prepare
    - converge

verifier:
  name: ansible
  enabled: true
