---
# Copyright (C) 2023 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Update cache
  hosts: k8s
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: true
        cache_valid_time: 3600

- name: Harden hosts
  hosts: all
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Setup harden_linux role
      include_role:
        name: githubixx.harden_linux

- name: Setup Wireguard VPN
  hosts: vpn
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Setup wireguard role
      include_role:
        name: githubixx.ansible_role_wireguard

- name: Setup Kubernetes certificates
  hosts: k8s_assets
  become: true
  gather_facts: false
  tasks:
    - name: Install cfssl
      include_role:
        name: githubixx.cfssl

    - name: Generate etcd and K8s TLS certificates
      include_role:
        name: githubixx.kubernetes_ca

    - name: Copy certificate files from assets to local host
      ansible.posix.synchronize:
        mode: pull
        src: "{{ k8s_config_directory }}"
        dest: "/tmp"

- name: Setup etcd
  hosts: k8s_etcd
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include etcd role
      include_role:
        name: githubixx.etcd

- name: Setup Kubernetes authentication files
  hosts: k8s_assets
  become: true
  gather_facts: true
  tasks:
    - name: Install kubectl
      ansible.builtin.include_role:
        name: githubixx.kubectl

    - name: Generate kubelet kubeconfig
      ansible.builtin.include_tasks:
        file: "tasks/kubelets.yml"

    - name: Generate kube-proxy kubeconfig
      ansible.builtin.include_tasks:
        file: "tasks/kube-proxy.yml"

    - name: Generate kube-controller-manager kubeconfig
      ansible.builtin.include_tasks:
        file: "tasks/kube-controller-manager.yml"

    - name: Generate kube-scheduler kubeconfig
      ansible.builtin.include_tasks:
        file: "tasks/kube-scheduler.yml"

    - name: Generate kube-admin-user kubeconfig
      ansible.builtin.include_tasks:
        file: "tasks/kube-admin-user.yml"

    - name: Generate kubeencryption configuration
      ansible.builtin.include_tasks:
        file: "tasks/kubeencryptionconfig.yml"

    - name: Copy configuration files from assets to local host
      ansible.posix.synchronize:
        mode: pull
        src: "{{ k8s_config_directory }}"
        dest: "/tmp"

- name: Setup Kubernetes tooling
  hosts: k8s_assets
  become: true
  gather_facts: true
  tasks:
    - name: Generate configuration for kubectl
      ansible.builtin.include_tasks:
        file: "tasks/kubectlconfig.yml"

    - name: Install support packages
      ansible.builtin.package:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - conntrack
          - python3-pip

    - name: Install kubernetes Python package
      ansible.builtin.pip:
        name: kubernetes
        state: present

    - name: Install Helm role
      ansible.builtin.include_role:
        name: gantsign.helm

- name: Setup Kubernetes controller
  hosts: k8s_controller
  become: true
  gather_facts: true
  tasks:
    - name: Include kubernetes_controller role
      ansible.builtin.include_role:
        name: githubixx.kubernetes_controller

- name: Setup containerd
  hosts: k8s_worker
  become: true
  gather_facts: true
  tasks:
    - name: Include containerd role
      ansible.builtin.include_role:
        name: githubixx.containerd

- name: Setup Kubernetes worker
  hosts: k8s_worker
  become: true
  gather_facts: true
  tasks:
    - name: Include kubernetes_worker role
      ansible.builtin.include_role:
        name: githubixx.kubernetes_worker

- name: Setup Cilium CLI
  hosts: test-assets
  become: true
  tasks:
    - name: Include cilium_cli role
      ansible.builtin.include_role:
        name: githubixx.cilium_cli
