---
# Copyright (C) 2020-2025 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Verify setup
  hosts: test-assets
  environment:
    K8S_AUTH_KUBECONFIG: "{{ k8s_admin_conf_dir }}/admin.kubeconfig"
  tasks:
    - name: Fetch Cilium DaemonSet information
      kubernetes.core.k8s_info:
        api_version: v1
        kind: DaemonSet
        name: cilium
        namespace: cilium
      register: cilium__daemonset_info

    - name: Print DaemonSet JSON blob
      ansible.builtin.debug:
        var: cilium__daemonset_info
      when: ansible_verbosity > 1

    - name: There should be a DaemonSet called cilium
      ansible.builtin.assert:
        that:
          - cilium__daemonset_info.resources[0].metadata.name == "cilium"

    - name: There should be at least one Cilium pod running
      ansible.builtin.assert:
        that:
          - (cilium__daemonset_info.resources[0].status.numberReady | default(0) | int ) >= 1

    - name: Fetch Cilium status
      become: true
      become_user: vagrant
      ansible.builtin.command:
        cmd: cilium -n cilium status --output json
      register: cilium__json_status
      changed_when: false

    - name: Register cilium pods unavailable
      ansible.builtin.set_fact:
        cilium__cilium_pods_running: "{{ cilium__json_status | to_json | from_json | community.general.json_query(json_query) }}"
      vars:
        json_query: "pod_state.cilium.Unavailable"

    - name: Check if cilium pods unavailable is 0
      ansible.builtin.fail:
        msg: "Ja: {{ cilium__cilium_pods_running }}"
      when: cilium__cilium_pods_running | int != 0

    - name: Register cilium-operator pods unavailable
      ansible.builtin.set_fact:
        cilium__cilium_operator_pods_running: "{{ cilium__json_status | to_json | from_json | community.general.json_query(json_query) }}"
      vars:
        json_query: 'pod_state."cilium-operator".Unavailable'

    - name: Check if cilium-operator pods unavailable is 0
      ansible.builtin.fail:
        msg: "Ja: {{ cilium__cilium_operator_pods_running }}"
      when: cilium__cilium_operator_pods_running | int != 0

    - name: Print Cilium status output
      ansible.builtin.debug:
        var: cilium__json_status.stdout
      when: ansible_verbosity > 1
