---
# Copyright (C) 2020-2025 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

wireguard_address: "10.10.10.5/24"
wireguard_port: 51820
wireguard_persistent_keepalive: "30"
wireguard_endpoint: "172.16.10.5"

k8s_admin_api_endpoint_host: "{{ hostvars[groups['k8s_controller'] | first]['ansible_' + hostvars[groups['k8s_controller'] | first]['k8s_interface']].ipv4.address }}"
k8s_admin_api_endpoint_port: "16443"
